import React, {useState} from 'react';
import {SafeAreaView, View, Text, TextInput, TouchableOpacity, StyleSheet, ScrollView} from 'react-native';
import {COLORS} from '../../constants/colors';
import {PARKS} from '../../constants/parks';
import {CATEGORIES} from '../../constants/categories';
import {useParkStore} from '../../stores/parkStore';
import {useListStore} from '../../stores/listStore';

const landsByPark={
  'magic-kingdom':['Main Street, U.S.A.','Adventureland','Frontierland','Liberty Square','Fantasyland','Tomorrowland'],
  epcot:['World Celebration','World Discovery','World Nature','World Showcase - France','World Showcase - Norway','World Showcase - America','Other'],
  'hollywood-studios':['Hollywood Boulevard','Sunset Boulevard','Toy Story Land','Star Wars: Galaxy’s Edge','Echo Lake','Other'],
  'animal-kingdom':['Discovery Island','Pandora','Africa','Asia','DinoLand U.S.A.','Other'],
};
export default function AddCustomItemScreen({navigation}) {
  const activePark=useParkStore((s)=>s.activePark); const addCustomItem=useListStore((s)=>s.addCustomItem);
  const [name,setName]=useState(''); const [category,setCategory]=useState('experience'); const [parkSlug,setParkSlug]=useState(activePark); const [landName,setLandName]=useState(landsByPark[activePark][0]); const [priority,setPriority]=useState('nice_to_have'); const [notes,setNotes]=useState('');
  const valid=name.trim().length>=2;
  async function save(){if(!valid)return; await addCustomItem({name:name.trim(),category,parkSlug,landName,priority,notes,description:'Custom wishlist reminder.'}); navigation.goBack();}
  return <SafeAreaView style={styles.screen}><View style={styles.header}><TouchableOpacity onPress={()=>navigation.goBack()}><Text style={styles.link}>Cancel</Text></TouchableOpacity><Text style={styles.title}>Add Custom Item</Text><TouchableOpacity onPress={save}><Text style={[styles.link,!valid&&styles.disabled]}>Save</Text></TouchableOpacity></View><ScrollView contentContainerStyle={styles.content}><Text style={styles.label}>Item Name*</Text><TextInput value={name} onChangeText={setName} style={styles.input} placeholder="Example: Buy a popcorn bucket"/><Text style={styles.label}>Category*</Text><View style={styles.wrap}>{CATEGORIES.filter((c)=>c.key!=='all').map((c)=><TouchableOpacity key={c.key} onPress={()=>setCategory(c.key)} style={[styles.chip,category===c.key&&styles.active]}><Text>{c.icon} {c.label}</Text></TouchableOpacity>)}</View><Text style={styles.label}>Park*</Text><View style={styles.wrap}>{PARKS.map((p)=><TouchableOpacity key={p.slug} onPress={()=>{setParkSlug(p.slug);setLandName(landsByPark[p.slug][0]);}} style={[styles.chip,parkSlug===p.slug&&styles.active]}><Text>{p.shortName}</Text></TouchableOpacity>)}</View><Text style={styles.label}>Land/Area*</Text><View style={styles.wrap}>{landsByPark[parkSlug].map((l)=><TouchableOpacity key={l} onPress={()=>setLandName(l)} style={[styles.chip,landName===l&&styles.active]}><Text>{l}</Text></TouchableOpacity>)}</View><Text style={styles.label}>Priority</Text><View style={styles.row}><TouchableOpacity onPress={()=>setPriority('must_do')} style={[styles.segment,priority==='must_do'&&styles.active]}><Text>Must Do ⭐</Text></TouchableOpacity><TouchableOpacity onPress={()=>setPriority('nice_to_have')} style={[styles.segment,priority==='nice_to_have'&&styles.active]}><Text>Nice to Have</Text></TouchableOpacity></View><Text style={styles.label}>Notes</Text><TextInput value={notes} onChangeText={setNotes} multiline style={[styles.input,{height:90,textAlignVertical:'top'}]} placeholder="Optional note"/><TouchableOpacity style={[styles.save,!valid&&{opacity:.4}]} onPress={save}><Text style={styles.saveText}>Save Custom Item</Text></TouchableOpacity></ScrollView></SafeAreaView>
}
const styles=StyleSheet.create({screen:{flex:1,backgroundColor:COLORS.background},header:{height:56,flexDirection:'row',alignItems:'center',justifyContent:'space-between',paddingHorizontal:16,borderBottomWidth:1,borderBottomColor:COLORS.surface},title:{fontWeight:'900',fontSize:17},link:{color:COLORS.accentGold,fontWeight:'900'},disabled:{color:COLORS.pinInactive},content:{padding:16},label:{fontWeight:'900',marginTop:18,marginBottom:8},input:{backgroundColor:COLORS.surface,borderRadius:12,padding:12,fontSize:16},wrap:{flexDirection:'row',flexWrap:'wrap',gap:8},chip:{backgroundColor:COLORS.surface,borderRadius:16,paddingHorizontal:12,paddingVertical:9},active:{backgroundColor:COLORS.accentGold},row:{flexDirection:'row',gap:8},segment:{flex:1,backgroundColor:COLORS.surface,borderRadius:12,padding:14,alignItems:'center'},save:{height:54,borderRadius:12,backgroundColor:COLORS.accentGold,alignItems:'center',justifyContent:'center',marginTop:26},saveText:{fontWeight:'900',fontSize:16,color:COLORS.textPrimary}});
