import React, {useState} from 'react';
import {Modal, View, Text, TouchableOpacity, StyleSheet, TextInput, ScrollView} from 'react-native';
import {COLORS} from '../constants/colors';
import {CATEGORY_ICONS, CATEGORY_LABELS} from '../constants/categories';
import {useListStore} from '../stores/listStore';

export default function DetailModal({item, visible, onClose}) {
  const addItem=useListStore((s)=>s.addItem); const isOnList=useListStore((s)=>item?.id?s.isOnList(item.id,item.parkSlug):false);
  const lists=useListStore((s)=>s.lists); const updatePriority=useListStore((s)=>s.updatePriority); const updateNotes=useListStore((s)=>s.updateNotes); const removeItem=useListStore((s)=>s.removeItem); const completeItem=useListStore((s)=>s.completeItem); const addSubItem=useListStore((s)=>s.addSubItem);
  const listItem = item ? Object.values(lists).flat().find((i)=>i.attractionId===item.id || i.id===item.id) : null;
  const [note,setNote]=useState(listItem?.notes||'');
  if(!item) return null;
  const display={...item,...(listItem||{})}; const color=COLORS[display.category]||COLORS.accentGold;
  async function handleAdd(){ const added=await addItem(item); if(item.category==='dining' && item.menuItems?.length){ for (const m of item.menuItems.filter((m)=>m.isIconic).slice(0,1)) await addSubItem(added.id,{menuItemId:m.id,name:m.name}); } }
  return <Modal visible={visible} animationType="slide" transparent onRequestClose={onClose}><View style={styles.backdrop}><View style={styles.sheet}><View style={styles.handle}/><ScrollView><View style={[styles.hero,{backgroundColor:color}]}><Text style={styles.heroIcon}>{CATEGORY_ICONS[display.category]}</Text></View><View style={styles.content}><View style={[styles.badge,{backgroundColor:color}]}><Text style={styles.badgeText}>{CATEGORY_LABELS[display.category]}</Text></View><Text style={styles.title}>{display.name}</Text><Text style={styles.meta}>{display.landName}{display.lightningLane?' • ⚡ Lightning Lane':''}</Text><Text style={styles.desc}>{display.description || 'Custom wishlist item.'}</Text>{display.heightRequirement?<Text style={styles.field}>Height: {display.heightRequirement}</Text>:null}{display.diningType?<Text style={styles.field}>Dining type: {display.diningType.replace('_',' ')}</Text>:null}{listItem?<View style={styles.priority}><TouchableOpacity onPress={()=>updatePriority(listItem.id,'must_do')} style={[styles.priorityBtn,listItem.priority==='must_do'&&styles.priorityActive]}><Text>Must Do ⭐</Text></TouchableOpacity><TouchableOpacity onPress={()=>updatePriority(listItem.id,'nice_to_have')} style={[styles.priorityBtn,listItem.priority==='nice_to_have'&&styles.priorityActive]}><Text>Nice to Have</Text></TouchableOpacity></View>:null}{display.category==='dining'&&display.menuItems?.length?<View style={styles.menu}><Text style={styles.section}>Menu reminders</Text>{display.menuItems.map((m)=><TouchableOpacity key={m.id} style={styles.menuRow} onPress={async()=>{let li=listItem; if(!li) li=await addItem(item); await addSubItem(li.id,{menuItemId:m.id,name:m.name});}}><Text>{m.isIconic?'⭐ ':''}{m.name}</Text><Text style={styles.addSmall}>Add</Text></TouchableOpacity>)}</View>:null}{listItem?<><Text style={styles.section}>Notes</Text><TextInput multiline value={note} onChangeText={setNote} onBlur={()=>updateNotes(listItem.id,note)} placeholder="Add a note..." style={styles.notes}/></>:null}{!isOnList && !listItem ? <TouchableOpacity style={styles.primary} onPress={handleAdd}><Text style={styles.primaryText}>Add to My List</Text></TouchableOpacity> : <><Text style={styles.added}>Already on your list ✓</Text><TouchableOpacity style={styles.secondary} onPress={()=>completeItem(listItem.id,true)}><Text style={styles.secondaryText}>Mark as Done</Text></TouchableOpacity><TouchableOpacity onPress={()=>removeItem(listItem.id)}><Text style={styles.remove}>Remove from List</Text></TouchableOpacity></>}<TouchableOpacity style={styles.close} onPress={onClose}><Text style={styles.closeText}>Done</Text></TouchableOpacity></View></ScrollView></View></View></Modal>
}
const styles=StyleSheet.create({backdrop:{flex:1,backgroundColor:'rgba(0,0,0,.35)',justifyContent:'flex-end'},sheet:{height:'82%',backgroundColor:COLORS.background,borderTopLeftRadius:20,borderTopRightRadius:20,overflow:'hidden'},handle:{width:36,height:4,borderRadius:2,backgroundColor:COLORS.pinInactive,alignSelf:'center',marginVertical:10},hero:{height:170,alignItems:'center',justifyContent:'center'},heroIcon:{fontSize:72},content:{padding:16},badge:{alignSelf:'flex-start',paddingHorizontal:10,paddingVertical:5,borderRadius:12},badgeText:{color:COLORS.white,fontWeight:'800'},title:{fontSize:24,fontWeight:'900',marginTop:12,color:COLORS.textPrimary},meta:{color:COLORS.textSecondary,marginTop:4},desc:{fontSize:15,lineHeight:22,marginTop:16,color:COLORS.textPrimary},field:{marginTop:10,fontWeight:'700',color:COLORS.textPrimary},primary:{height:52,borderRadius:12,backgroundColor:COLORS.accentGold,alignItems:'center',justifyContent:'center',marginTop:18},primaryText:{fontWeight:'900',fontSize:16,color:COLORS.textPrimary},added:{backgroundColor:COLORS.surface,padding:14,borderRadius:12,textAlign:'center',marginTop:18,fontWeight:'900',color:COLORS.accentGold},secondary:{padding:12,alignItems:'center'},secondaryText:{color:COLORS.success,fontWeight:'800'},remove:{color:COLORS.error,textAlign:'center',fontWeight:'800',padding:10},close:{height:48,alignItems:'center',justifyContent:'center'},closeText:{fontWeight:'900',color:COLORS.textSecondary},priority:{flexDirection:'row',gap:8,marginTop:16},priorityBtn:{flex:1,padding:12,borderRadius:12,backgroundColor:COLORS.surface,alignItems:'center'},priorityActive:{borderWidth:2,borderColor:COLORS.accentGold},section:{fontSize:18,fontWeight:'900',marginTop:18,marginBottom:8},menuRow:{flexDirection:'row',justifyContent:'space-between',paddingVertical:12,borderBottomWidth:1,borderBottomColor:COLORS.surface},addSmall:{color:COLORS.accentGold,fontWeight:'900'},notes:{backgroundColor:COLORS.surface,minHeight:80,borderRadius:12,padding:12,textAlignVertical:'top'}});
