import React from 'react';
import {SafeAreaView, View, Text, TouchableOpacity, StyleSheet, ScrollView, Switch} from 'react-native';
import {COLORS} from '../../constants/colors';
import {useSettingsStore} from '../../stores/settingsStore';
export default function SettingsScreen({navigation}) {
  const backupEnabled=useSettingsStore((s)=>s.backupEnabled); const setBackupEnabled=useSettingsStore((s)=>s.setBackupEnabled); const notificationsEnabled=useSettingsStore((s)=>s.notificationsEnabled); const setNotificationsEnabled=useSettingsStore((s)=>s.setNotificationsEnabled);
  return <SafeAreaView style={styles.screen}><View style={styles.header}><TouchableOpacity onPress={()=>navigation.goBack()}><Text style={styles.link}>Back</Text></TouchableOpacity><Text style={styles.title}>Settings</Text><View style={{width:40}}/></View><ScrollView contentContainerStyle={styles.content}><Text style={styles.section}>Backup & Sync</Text><View style={styles.row}><View><Text style={styles.rowTitle}>Anonymous cloud backup</Text><Text style={styles.rowSub}>Placeholder until Supabase is configured.</Text></View><Switch value={backupEnabled} onValueChange={setBackupEnabled}/></View><Text style={styles.section}>Notifications</Text><View style={styles.row}><View><Text style={styles.rowTitle}>Morning reminders</Text><Text style={styles.rowSub}>Requires native notification setup.</Text></View><Switch value={notificationsEnabled} onValueChange={setNotificationsEnabled}/></View><Text style={styles.section}>Trip Dates</Text><View style={styles.card}><Text style={styles.rowTitle}>Date picker placeholder</Text><Text style={styles.rowSub}>Add native date picker and store dates in settingsStore.tripDates.</Text></View><Text style={styles.section}>Data</Text><View style={styles.card}><Text style={styles.rowTitle}>Clear completed / clear all data</Text><Text style={styles.rowSub}>Destructive actions should be added with confirmation modals.</Text></View><Text style={styles.section}>About</Text><Text style={styles.rowSub}>Wish List: Disney Park Planner prototype v0.1.0</Text></ScrollView></SafeAreaView>
}
const styles=StyleSheet.create({screen:{flex:1,backgroundColor:COLORS.background},header:{height:56,flexDirection:'row',alignItems:'center',justifyContent:'space-between',paddingHorizontal:16,borderBottomWidth:1,borderBottomColor:COLORS.surface},title:{fontWeight:'900',fontSize:18},link:{color:COLORS.accentGold,fontWeight:'900'},content:{padding:16},section:{fontSize:19,fontWeight:'900',marginTop:20,marginBottom:10},row:{backgroundColor:COLORS.white,borderRadius:16,padding:16,flexDirection:'row',justifyContent:'space-between',alignItems:'center'},card:{backgroundColor:COLORS.white,borderRadius:16,padding:16},rowTitle:{fontWeight:'900',fontSize:16,color:COLORS.textPrimary},rowSub:{color:COLORS.textSecondary,marginTop:4,lineHeight:20,maxWidth:250}});
